### ISSUE TITLE
Applying UserSchema to the login section or come up with an alternative way of setting up user profile

### ISSUE THREAD

**Issue by gumsanaung** [aloha-supply-co/ManoaCart#14]

**Comment by gumsanaung** [comment]
Currently trying to create an account first using accounts-base and if no error, save the other data, such as name, uh id etc into a separate collection, UserSchema. This UserSchema will be tied to the user and be made editable on the profile page.

**Comment by WenEddie** [comment]
Created Users Collection and UserSchema, and made default Users.
