### ISSUE TITLE
admin feature

### ISSUE THREAD

**Issue by derrickluyen** [aloha-supply-co/ManoaCart#31]
-Report button for each item sold. Will be redirected to another Report Form. (Jeffrey)
-For Admin account, an admin page is on NavBar that displays the Report Log (click on Report and redirect to new page to allow resolve), all users in ManoaCart (allow delete User, assign roles). Admin cannot buy or sell. Displays Buying Items but only allow delete. (Eddie)
-Send email notifications to users associated with changes done by Admin. (Gum)

**Comment by WenEddie** [comment]
Admin account now has an Admin Page. It displays all the Items, Reports, and Users. The admin has the ability to delete any one of the collections.
This Admin Page has been merged with the Master branch.

**Comment by JeffreyYu1** [comment]
Admin account only shows admin page

**Comment by gumsanaung** [comment]
completed
